name: Check Docker Images are built without any errors

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build simuserve-api
        run:
          docker build -f ./src/api/Dockerfile ./src/api
      - name: Build simuserve-auth
        run:
          docker build -f ./src/auth/Dockerfile ./src/auth
      - name: Build simuserve-frontend
        run:
          docker build -f ./src/frontend/Dockerfile ./src/frontend
      - name: Build simuserve-monitor
        run:
          docker build -f ./src/monitor/Dockerfile ./src/monitor
      - name: Build simuserve-similarity
        run:
          docker build -f ./src/similarity/Dockerfile ./src/similarity
      - name: Build simuserve-data-population
        run:
          docker build -f ./src/data_population/Dockerfile ./src/data_population
      - name: Build services-ready
        run:
          docker build -f ./src/services_ready/Dockerfile ./src/services_ready
